name: flask app deployment to ACI & AKS

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}

    # deploy:
    #     needs: build
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: 'Login via Azure CLI'
    #       uses: azure/login@v1
    #       with:
    #         creds: ${{ secrets.AZURE_CREDENTIALS }}

    #     - name: 'Deploy to Azure Container Instances'
    #       uses: 'azure/aci-deploy@v1'
    #       with:
    #         resource-group: ${{ secrets.RESOURCE_GROUP }}
    #         dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
    #         image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}
    #         registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
    #         registry-username: ${{ secrets.REGISTRY_USERNAME }}
    #         registry-password: ${{ secrets.REGISTRY_PASSWORD }}
    #         name: aci-flaskapp
    #         location: 'korea central'
            
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Set AKS context
          id: set-context
          uses: azure/aks-set-context@v3
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            cluster-name: ${{ secrets.CLUSTER_NAME }}

        - name: Setup kubectl
          id: install-kubectl
          uses: azure/setup-kubectl@v3
        
        - name: Deploy to AKS
          id: deploy-aks
          uses: Azure/k8s-deploy@v4
          with:
            namespace: 'default'
            manifests: |
              ossca-devops.yaml
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flaskapp:${{ github.sha }}
            pull-images: false 

